# Generated by Django 3.0.6 on 2020-05-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dute_date',
            new_name='due_date',
        ),
    ]
