# Generated by Django 3.0.6 on 2020-06-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('PM', 1), ('SELf', 2)], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[('Open', 1), ('InProgress', 2), ('Completed', 3), ('closed', 4)], default=1),
        ),
    ]
