# Generated by Django 3.0.6 on 2020-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200601_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'PM'), (2, 'SELF')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (2, 'InProgress'), (3, 'Completed'), (4, 'closed')], default=1),
        ),
    ]
