# Generated by Django 3.0.6 on 2020-06-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200604_1108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
