# Generated by Django 3.0.6 on 2020-07-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200607_1709'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Kanban_Task',
        ),
    ]
