# Generated by Django 3.0.6 on 2020-07-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20200713_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
