# Generated by Django 3.0.6 on 2020-07-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20200713_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Kanban_Task',
        ),
    ]
