# Generated by Django 3.0.6 on 2020-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ManyToManyField(related_name='user', to='user.User'),
        ),
    ]
