# Generated by Django 3.0.6 on 2020-06-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200608_1413'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
