# Generated by Django 3.0.6 on 2020-07-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200608_1414'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Kanban_Project',
        ),
    ]
