# Generated by Django 3.0.6 on 2020-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='autority',
            field=models.IntegerField(choices=[('NORMAL', 2), ('ADMIN', 1)], default=1),
        ),
    ]
