# Generated by Django 3.0.6 on 2020-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200601_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
