# Generated by Django 3.0.6 on 2020-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200601_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='autority',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'NORMAL')], default=1),
        ),
    ]
